"""Add classification to stock and buy_price to quotation items

Revision ID: 3db5b9245912
Revises: 4be1dc5a223d
Create Date: 2026-05-04 23:27:15.768854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db5b9245912'
down_revision = '4be1dc5a223d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buy_price', sa.Numeric(precision=12, scale=2), nullable=True))

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['batch_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('status')
        batch_op.drop_column('item_type')

    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.drop_column('buy_price')

    # ### end Alembic commands ###
